### ISSUE TITLE
Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by yizou10** [web3-storage/w3up#1209]
Hi,

I am now using @web3-storage/w3up-client package to upload my data, but get the following error:

Error [ERR_REQUIRE_ESM]: require() of ES Module ....../node_modules/@web3-storage/w3up-client/src/index.node.js from xxx.ts not supported. Instead change the require of index.node.js in xxx.ts to a dynamic import() which is available in all CommonJS modules.

Looks like the package is only esm compatible? I did not encounter the error when using old web3.storage package.
Any suggestions for this error? How do I solve it? And will you support CJS(CommonJS) later? 

Thanks!

**Comment by shubhamrejolut** [comment]
Facing the same issue version 11.2.0

**Comment by bever1995** [comment]
Facing the same issue version 11.2.0

**Comment by orpheuslummis** [comment]
I tried downgrading version of the package to ^10, ^9, ^8 , ^7 and still faced the same issue...

**Comment by nolifelover** [comment]
<img width="949" alt="2566-12-02_11 59 21" src="https://github.com/web3-storage/w3up/assets/132048/73dbb69a-aa8e-4c26-8f37-963adba9225b">
Same issue using in NestJS

**Comment by anvabr** [comment]
Facing the same issue, please someone from web.storage comment on this?

**Comment by magror** [comment]
This is happening to me too. I am trying to use this in a Docker Image with typescript.

**Comment by alanshaw** [comment]
The web3.storage client is ESM only. You'll need to update your codebase or transform it to CJS yourself.

**Comment by achal-singh** [comment]
Although this issue is marked as **`closed`**, for those who still want to know a working solution, here’s one. I encountered the same issue while integrating **`@web3-storage/w3up-client`** into my CJS-based TypeScript project. I tried using dynamic imports, but that didn’t resolve the issue for me.

So after a bit of search I found an approach that uses the **[esbuild](https://esbuild.github.io/)** module bundler. This is a relatively light weight approach which doesn't require any changes to **`package.json`** or **`tsconfig.json`**, or any other code changes to the rest of my typescript project, which was the case with most of the other suggested solutions.

Here are the steps to this approach:

1. Install the **[esbuild](https://www.npmjs.com/package/esbuild)** package using:
```shell
npm i esbuild
```
2. Create a file which will be used an input for the esbuild to create a **`.js`** file as a build. In my example, I created a file named **`index.ts`** under the **`esm`** folder within the **`src`** folder of my project, hence the path: `**src/esm/index.ts**.
3. In the **`index.ts`** file created above, make sure to import and export all the required functions and properties that you wish to access or you can simply import everything using a namespace import (using **`import * as`** ) from the **`w3up-client`** library. Here's how the **`index.ts`** file looked in my case:

```ts
import * as W3SClient from '@web3-storage/w3up-client'
import { fromEmail } from '@web3-storage/did-mailto'

export { W3SClient, fromEmail as Email }
```

4. Now you need to add a command in your package.json mentioning the input and output of the typescript file that you wish to bundle using the **`esbuild`** bundler. The raw format of this command is:
**`esbuild --platform=node <path-to-input-file> --bundle --outfile=<path-to-output-file>`**
I created a script named **`w3s-build`** and it looked like this:

```json
 "scripts": {
    "w3s-build": "esbuild --platform=node src/esm/index.ts --bundle --outfile=src/esm/bundle.js",
    "compile": "npm run w3s-build && tsc -p ."
   }
```
**Note:** You must execute the **`w3s-build`** command first so that it's bundle code can be used in the project compilation, see **_`compile`_** command above.

5. The exported stuff can be accessed anywhere in your project by referring to the **`index.js`** file (which will be created once you execute a build command using the esbuild library, reference to this will be in the **`package.json`** in step 5). In my code this is how I imported the contents from the bundle file:

```ts
import { join } from 'path'
const { W3SClient, Email } = require(join(process.cwd(), '/src/esm/bundle.js'))

(async () => {
  const client = await W3SClient.create()
  console.log(client);
})();
```
Hope this helps.
